version: 0.2
env:
  parameter-store:
    DB_NAME: "/MY/DBNAME"
    DB_USER: "/MY/DBUSER"
    DB_PASSWORD: "/MY/DBPASSWORD"
    DB_HOST: "/MY/DBHOST"


phases:
  build:
    commands:
      - sed -i 's|DBNAME|'$DB_NAME'|' wp-config.php
      - sed -i 's|DBUSER|'$DB_USER'|' wp-config.php
      - sed -i 's|DBPASSWORD|'$DB_PASSWORD'|' wp-config.php
      - sed -i 's|DBHOST|'$DB_HOST'|' wp-config.php
      
    
artifacts:
  files:
    - "**/*"
