version: 0.2
env:
  parameter-store:
    DB_NAME: "/MY/DBNAME"
    DB_USER: "/MY/DBUSER"
    DB_PASSWORD: "/MY/DBPASSWORD"
    DB_HOST: "DBHOST"


phases:
  pre_build:
    commands:
      - echo Running Pre-Build script...
  build:
    commands:
      - mv wp-config-sample.php wp-config.php
  post_build:
    commands:
      - echo Build completed on `date`    
      
      
artifacts:
  files:
    - "**/*"
